import test from "node:test";
import assert from "node:assert/strict";
import { handoffAgreementFilename, handoffArchiveFilename, handoffDocumentUnits, safeFilenamePart } from "../src/lib/services/handoff-documents.mjs";
import { buildZipBuffer } from "../src/lib/services/zip-buffer.mjs";
import { handoffEmailMessage } from "../src/lib/services/handoff-email-message.mjs";

function snapshot(modules) { return { issuedAt:"2026-09-01T00:00:00.000Z",packet:{id:"internal",version:1},recipient:{name:"Test Client",email:"client@example.com"},draftData:{projectSummary:{clientBusinessName:"Test Client"}},policyModules:modules }; }
const policyModule = (key,title,content=key) => ({key,title,category:"Test",description:"Description",content});

test("one selected module becomes one safely named PDF",()=>{const units=handoffDocumentUnits(snapshot([policyModule("summary","Project / Completion: Summary?")]));assert.equal(units.length,1);assert.equal(units[0].filename,"01-Project-Completion-Summary.pdf");});
test("nine snapshot modules become nine PDFs in snapshot order",()=>{const modules=Array.from({length:9},(_,i)=>policyModule(`key-${i}`,`Document ${i+1}`));const units=handoffDocumentUnits(snapshot(modules));assert.equal(units.length,9);assert.deepEqual(units.map(x=>x.key),modules.map(x=>x.key));assert.equal(units[8].filename,"09-Document-9.pdf");});
test("unselected modules are absent and template mutation cannot alter issued units",()=>{const frozen=snapshot([policyModule("selected","Selected","Frozen content")]);const mutableTemplate=[policyModule("selected","Changed"),policyModule("other","Other")];assert.deepEqual(handoffDocumentUnits(frozen).map(x=>x.title),["Selected"]);assert.equal(mutableTemplate.length,2);});
test("filenames and archive name are deterministic and filesystem safe",()=>{const value="  Téšt & Client / LLC .. ";assert.equal(safeFilenamePart(value),"Test-and-Client-LLC");const first=handoffArchiveFilename(snapshot([]));const second=handoffArchiveFilename(snapshot([]));assert.equal(first,"WebDashy-Handoff-Test-Client-v1.zip");assert.equal(first,second);});
test("accepted rendering target is only the immutable final acceptance unit",()=>{const units=handoffDocumentUnits(snapshot([policyModule("summary","Summary"),policyModule("final_acceptance_sign_off","Final Acceptance & Sign-Off")]));assert.deepEqual(units.filter(x=>x.key==="final_acceptance_sign_off").map(x=>x.filename),["02-Final-Acceptance-and-Sign-Off.pdf"]);});
test("legacy packets retain a single combined document unit",()=>{const legacy={...snapshot(undefined)};delete legacy.policyModules;assert.deepEqual(handoffDocumentUnits(legacy).map(x=>[x.key,x.legacy]),[["legacy-packet",true]]);});
test("ZIP contains the expected ordered snapshot filenames",async()=>{const units=handoffDocumentUnits(snapshot([policyModule("one","First"),policyModule("two","Second")]));const zip=await buildZipBuffer(units.map((unit)=>({filename:unit.filename,buffer:Buffer.from(unit.key)})),"2026-09-01T00:00:00.000Z");const binary=zip.toString("latin1");assert.ok(binary.includes("01-First.pdf"));assert.ok(binary.includes("02-Second.pdf"));assert.ok(binary.indexOf("01-First.pdf")<binary.indexOf("02-Second.pdf"));});
test("handoff email has exactly one ZIP attachment",()=>{const message=handoffEmailMessage({contactName:"Client",handoffUrl:"https://example.com/h/token",zipBuffer:Buffer.from("zip"),zipFilename:"handoff.zip"});assert.equal(message.attachments.length,1);assert.equal(message.attachments[0].contentType,"application/zip");assert.match(message.text,/attached ZIP contains/);});
test("Revision 3 uses one deterministic Client Agreement filename and rejects legacy acceptance units",()=>{const revision3={...snapshot([policyModule("final_acceptance_sign_off","Final Acceptance & Sign-Off"),policyModule("client_agreement","Client Agreement")]),snapshotSchemaVersion:3,template:{schemaVersion:3}};const units=handoffDocumentUnits(revision3);assert.deepEqual(units.map(({key,title,filename})=>({key,title,filename})),[{key:"client_agreement",title:"Client Agreement",filename:"WebDashy-Client-Agreement-Test-Client.pdf"}]);assert.equal(handoffAgreementFilename(revision3,true),"WebDashy-Signed-Client-Agreement-Test-Client.pdf");});
test("Revision 3 email attaches one agreement PDF and includes the secure signature link",()=>{const url="https://example.com/h/secure-token";const message=handoffEmailMessage({contactName:"Client",handoffUrl:url,pdfBuffer:Buffer.from("pdf"),pdfFilename:"WebDashy-Client-Agreement-Uribe-Construction.pdf",projectName:"Uribe Construction"});assert.equal(message.attachments.length,1);assert.equal(message.attachments[0].contentType,"application/pdf");assert.equal(message.attachments[0].filename,"WebDashy-Client-Agreement-Uribe-Construction.pdf");assert.match(message.subject,/Client Agreement Ready for Signature — Uribe Construction/);assert.match(message.text,/Review & Sign Agreement/);assert.match(message.text,/signed copy will be available/);assert.match(message.text,new RegExp(url));assert.doesNotMatch(message.text,/packet|ZIP/i);});
