import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { renderHandoffDocumentPdf, renderHandoffPdf } from "@/lib/handoff-pdf";
import { handoffAgreementFilename, handoffDocumentUnits, isRevision3Agreement } from "@/lib/services/handoff-documents.mjs";
import { findAdminHandoff } from "@/lib/services/handoff-download";
import type { HandoffPolicyModule } from "@/lib/services/public-handoff";
import { db } from "@/lib/db";
import { buildDraftHandoffPreview } from "@/lib/services/handoff-preview";
export const dynamic="force-dynamic";
export async function GET(request:Request,{params}:{params:Promise<{id:string;documentKey:string}>}) { if(!(await auth())?.user?.id)return NextResponse.json({error:"Unauthorized"},{status:401});const {id,documentKey}=await params;let found=await findAdminHandoff(id);if(!found){const packet=await db.handoffPacket.findUnique({where:{id},include:{acceptance:true,templateRevision:{include:{template:true}}}});if(packet?.status==="DRAFT"){const requestedRevision=Number(new URL(request.url).searchParams.get("templateRevision"));const revision=requestedRevision?await db.handoffTemplateRevision.findFirst({where:{templateId:packet.templateRevision.templateId,revision:requestedRevision},include:{template:true}}):packet.templateRevision;if(revision)found={packet,snapshot:buildDraftHandoffPreview(packet,revision)} as Awaited<ReturnType<typeof findAdminHandoff>>;}}if(found&&isRevision3Agreement(found.snapshot)&&documentKey!=="client_agreement")return NextResponse.json({error:"Not found"},{status:404});const unit=found&&(handoffDocumentUnits(found.snapshot) as {key:string;filename:string;legacy:boolean;module?:HandoffPolicyModule}[]).find((item)=>item.key===documentKey);if(!found||!unit)return NextResponse.json({error:"Not found"},{status:404});const pdf=unit.legacy?await renderHandoffPdf(found.snapshot,found.packet.snapshotHash??"DRAFT PREVIEW — NOT ISSUED",found.packet.acceptance):await renderHandoffDocumentPdf(found.snapshot,unit.module!,found.packet.snapshotHash??"DRAFT PREVIEW — NOT ISSUED",["client_agreement","final_acceptance_sign_off"].includes(unit.key)?found.packet.acceptance:null);const filename=isRevision3Agreement(found.snapshot)?handoffAgreementFilename(found.snapshot,Boolean(found.packet.acceptance)):unit.filename;return new NextResponse(new Uint8Array(pdf),{headers:{"Content-Type":"application/pdf","Content-Disposition":`inline; filename="${filename}"`,"Cache-Control":"private, no-store"}});}
