import type { Metadata } from "next";
import Image from "next/image";
import { randomBytes } from "node:crypto";
import { AcceptanceForm } from "@/components/handoff/acceptance-form";
import { validatePublicHandoff } from "@/lib/services/public-handoff";
import { handoffDocumentUnits } from "@/lib/services/handoff-documents.mjs";
import { isSafeHandoffPreviewEnabled } from "@/lib/services/handoff-dry-run.mjs";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Project Handoff | WebDashy", robots: { index: false, follow: false, nocache: true } };

const acceptanceDateTime = new Intl.DateTimeFormat("en-US", { year: "numeric", month: "long", day: "numeric", hour: "numeric", minute: "2-digit", timeZone: "America/Chicago", timeZoneName: "short" });

const title = (key: string) => key.replace(/([A-Z])/g, " $1").replace(/^./, c => c.toUpperCase());
function Values({ value }: { value: unknown }) {
  if (value == null || value === "") return null;
  if (Array.isArray(value)) return <div className="space-y-3">{value.map((item, i) => <Values key={i} value={item}/>)}</div>;
  if (typeof value === "object") return <dl className="grid gap-3 sm:grid-cols-2">{Object.entries(value as Record<string, unknown>).map(([k,v]) => v == null || v === "" ? null : <div key={k}><dt className="text-xs font-semibold uppercase tracking-wide text-slate-500">{title(k)}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-sm"><Values value={v}/></dd></div>)}</dl>;
  const text = String(value); const link = /^https:\/\//.test(text);
  return link ? <a href={text} target="_blank" rel="noopener noreferrer" className="text-blue-700 underline">{text}</a> : <>{text}</>;
}
export default async function HandoffPage({ params }: { params: Promise<{ token: string }> }) {
  const { token } = await params; const validation = await validatePublicHandoff(token, true); const result=validation.result;
  if (!result) return <main className="mx-auto max-w-xl px-6 py-24 text-center"><Image src="/brand/wordmark.png" width={180} height={34} alt="WebDashy" className="mx-auto"/><h1 className="mt-12 text-2xl font-bold">This handoff is unavailable</h1><p className="mt-3 text-slate-600">The link may be invalid or no longer active. Contact WebDashy for assistance.</p>{isSafeHandoffPreviewEnabled()?<p className="mt-4 font-mono text-xs text-amber-700">Development diagnostic: {validation.reason}</p>:null}</main>;
  const { packet, snapshot } = result; const draft = snapshot.draftData;
  const project = (draft.projectSummary ?? {}) as Record<string, unknown>;
  const modular = Array.isArray(snapshot.policyModules); const documents=handoffDocumentUnits(snapshot) as {key:string;title:string}[]; const singleAgreement=documents.length===1&&documents[0].key==="client_agreement";
  const revision3=singleAgreement&&snapshot.snapshotSchemaVersion===3;
  const facts = { project: { clientBusinessName: project.clientBusinessName, projectName: project.projectName }, website: { finalLiveUrl: (draft.websiteLaunch as Record<string,unknown>|undefined)?.liveUrl }, domain: { domainName: (draft.domain as Record<string,unknown>|undefined)?.primaryDomain }, clientCare: { selection: (draft.maintenanceSupport as Record<string,unknown>|undefined)?.clientCareDisposition }, warranty: { through: (draft.warranty as Record<string,unknown>|undefined)?.endDate } };
  if(revision3) {
    const projectName=String(project.projectName??packet.client.businessName);
    return <main className="mx-auto min-h-screen max-w-3xl px-5 py-10 text-slate-900">
      <header className="text-center"><Image src="/brand/wordmark.png" width={180} height={34} alt="WebDashy" className="mx-auto"/><p className="mt-10 text-xs font-semibold uppercase tracking-[0.22em] text-slate-500">Client Agreement</p><h1 className="mt-3 text-3xl font-bold text-[#172554]">Client Agreement</h1><p className="mt-2 text-slate-600">{packet.client.businessName} · {projectName}</p></header>
      <section className="mt-8 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-widest text-slate-500">Status</p><p className="mt-1 font-semibold text-[#172554]">{packet.acceptance?"Agreement Signed ✓":"Ready for Review"}</p></div><div className="flex flex-wrap gap-3"><a className="rounded-lg border border-[#1b2951] px-4 py-2.5 text-sm font-semibold text-[#1b2951]" href={`/api/h/${token}/documents/client_agreement`} target="_blank" rel="noopener noreferrer">View Agreement</a><a className="rounded-lg bg-[#1b2951] px-4 py-2.5 text-sm font-semibold text-white" href={`/api/h/${token}/documents/client_agreement`} download>{packet.acceptance?"Download Signed Agreement":"Download Agreement"}</a></div></div></section>
      {packet.acceptance?<section className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-7 text-emerald-950"><h2 className="text-2xl font-bold">Agreement Signed ✓</h2><div className="mt-4 space-y-1"><p>Signed by <strong>{packet.acceptance.typedName}</strong></p>{packet.acceptance.signerTitle?<p>Title: {packet.acceptance.signerTitle}</p>:null}<p>Date: {acceptanceDateTime.format(packet.acceptance.acceptedAt)}</p></div><a className="mt-6 inline-block rounded-lg bg-[#1b2951] px-5 py-3 font-semibold text-white" href={`/api/h/${token}/documents/client_agreement`} download>Download Signed Agreement</a></section>:<section className="mt-6 rounded-2xl border-2 border-[#1b2951] bg-white p-6 sm:p-8"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-500">Sign Agreement</p><h2 className="mt-2 text-2xl font-bold text-[#172554]">Electronic Signature</h2><p className="mt-2 text-sm leading-6 text-slate-600">Review the Client Agreement above, then complete each field and confirmation below.</p><div className="mt-6"><AcceptanceForm token={token} acknowledgmentText={snapshot.acceptanceText} submissionKey={randomBytes(18).toString("base64url")} clientBusinessName={packet.client.businessName} requireTitle/></div></section>}
    </main>;
  }
  return <main className="mx-auto max-w-4xl px-5 py-10 text-slate-900"><header className="border-b pb-7"><Image src="/brand/wordmark.png" width={180} height={34} alt="WebDashy"/><p className="mt-8 text-xs font-semibold uppercase tracking-widest text-slate-500">Project handoff · Version {snapshot.packet.version}</p><h1 className="mt-2 text-3xl font-bold">{String(project.projectName ?? packet.client.businessName)}</h1><p className="mt-2 text-slate-600">Prepared for {packet.client.businessName} · Issued {new Intl.DateTimeFormat("en-US", { dateStyle: "long" }).format(new Date(snapshot.issuedAt))}</p></header>
    {singleAgreement?<section className="mt-8 rounded-xl border-2 border-[#1b2951] bg-white p-6"><p className="text-xs font-semibold uppercase tracking-widest text-slate-500">Client Agreement</p><h2 className="mt-2 text-2xl font-bold">Website Project Completion, Ownership, Handoff, and Post-Launch Terms</h2><p className="mt-3 text-sm leading-6 text-slate-600">Review the complete Agreement before accepting it. After acceptance, the same PDF will include the immutable electronic acceptance certificate.</p><div className="mt-5 flex flex-wrap gap-3"><a className="rounded-lg border border-[#1b2951] px-5 py-3 text-sm font-semibold text-[#1b2951]" href={`/api/h/${token}/documents/client_agreement`} target="_blank" rel="noopener noreferrer">View Agreement</a><a className="rounded-lg bg-[#1b2951] px-5 py-3 text-sm font-semibold text-white" href={`/api/h/${token}/documents/client_agreement`} download>Download Agreement PDF</a></div></section>:<section className="mt-8 rounded-xl border bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">Handoff documents</h2><p className="mt-1 text-sm text-slate-600">Download each document separately or get the complete archive.</p></div><a className="rounded-lg bg-[#1b2951] px-5 py-3 text-sm font-semibold text-white" href={`/api/h/${token}/zip`}>Download All Documents (.zip)</a></div><ul className="mt-5 divide-y">{documents.map((document)=><li key={document.key} className="flex items-center justify-between gap-4 py-3 text-sm"><span>{document.title}</span><a className="font-semibold text-blue-700 underline" href={`/api/h/${token}/documents/${encodeURIComponent(document.key)}`} target="_blank" rel="noopener noreferrer">Download PDF</a></li>)}</ul></section>}<div className="space-y-6 py-8">{modular?<section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">Project details</h2><Values value={facts}/></section>:Object.entries(draft).map(([key,value]) => <section key={key} className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">{title(key)}</h2><Values value={value}/></section>)}
      {snapshot.checklist?<section className="rounded-xl border bg-white p-5"><h2 className="mb-4 text-lg font-bold">Handoff checklist</h2><ul className="space-y-2">{snapshot.checklist.map(item => <li key={item.key} className="flex justify-between gap-4 text-sm"><span>{item.label}</span><span className="font-medium">{title(item.status.toLowerCase())}</span></li>)}</ul></section>:null}
    </div>
    {packet.status==="COMPLETED"?<section className="mb-6 rounded-xl bg-emerald-50 p-6 text-emerald-950"><h2 className="text-xl font-bold">Handoff completed</h2><p className="mt-2">Completed {packet.completedAt?new Intl.DateTimeFormat("en-US",{dateStyle:"long"}).format(packet.completedAt):""} · Client Care: {String(((draft.maintenanceSupport??{}) as Record<string,unknown>).clientCareDisposition??"Confirmed")}</p></section>:null}<section className="rounded-xl border-2 border-[#1b2951] p-6"><h2 className="text-xl font-bold">{singleAgreement?"Accept Client Agreement":"Acceptance"}</h2><div className="mt-4">{packet.acceptance ? <div className="space-y-3"><p>Accepted by <strong>{packet.acceptance.typedName}</strong>{packet.acceptance.signerTitle ? `, ${packet.acceptance.signerTitle}` : ""} on {new Intl.DateTimeFormat("en-US", { dateStyle: "long", timeStyle: "short" }).format(packet.acceptance.acceptedAt)}.</p><a className="inline-block rounded-lg bg-[#1b2951] px-5 py-3 font-semibold text-white" href={singleAgreement?`/api/h/${token}/documents/client_agreement`:`/api/h/${token}/zip`}>{singleAgreement?"Download Accepted Agreement PDF":"Download Accepted Handoff ZIP"}</a></div> : <AcceptanceForm token={token} acknowledgmentText={snapshot.acceptanceText} submissionKey={randomBytes(18).toString("base64url")} clientBusinessName={packet.client.businessName}/>}</div></section>
  </main>;
}
